# Generated by Django 3.2.9 on 2021-11-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='song_list',
            field=models.ManyToManyField(to='songs.Song'),
        ),
    ]
