# Generated by Django 3.2.9 on 2021-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(default='03.26', editable=False, max_length=10),
        ),
    ]
