# Generated by Django 3.2.9 on 2021-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(default='01.40', editable=False, max_length=10),
        ),
    ]
