# Generated by Django 3.2.9 on 2021-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(default='02.33', editable=False, max_length=10),
        ),
    ]
